package gui;

import dao.DocenteDAO;
import dto.Docente;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

public class FraDocente extends javax.swing.JFrame {

    DocenteDAO docenteDAO = new DocenteDAO();
    boolean agregando = false;

    public FraDocente() {
        this.setSize(new Dimension(430, 340));
        this.setLocationRelativeTo(null);
        initComponents();
        habilitarBotonesMovimiento(false);
        habilitarBotonesEdicion(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnImprimir.setEnabled(false);
        habilitarCajasTexto(false);
    }

    public void habilitarBotonesMovimiento(boolean estaHabilitado) {
        btnPrimero.setEnabled(estaHabilitado);
        btnAnterior.setEnabled(estaHabilitado);
        btnSiguiente.setEnabled(estaHabilitado);
        btnUltimo.setEnabled(estaHabilitado);
    }

    public void habilitarBotonesEdicion(boolean estaHabilitado) {
        btnAgregar.setEnabled(estaHabilitado);
        btnModificar.setEnabled(estaHabilitado);
        btnEliminar.setEnabled(estaHabilitado);
        btnImprimir.setEnabled(estaHabilitado);

        btnGrabar.setEnabled(!estaHabilitado);
        btnCancelar.setEnabled(!estaHabilitado);
    }

    public void limpiarCajasTexto() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtFechaNaci.setText("");
        txtTalla.setText("");
        txtCorreo.setText("");
    }

    public void habilitarCajasTexto(boolean estaHabilitado) {
        txtCodigo.setEnabled(estaHabilitado);
        txtNombre.setEnabled(estaHabilitado);
        txtDireccion.setEnabled(estaHabilitado);
        txtFechaNaci.setEnabled(estaHabilitado);
        txtTalla.setEnabled(estaHabilitado);
        txtCorreo.setEnabled(estaHabilitado);
    }

    public void cargarDatos() {
        Docente docente = docenteDAO.getDocente();
        txtCodigo.setText(String.valueOf(docente.getCodigo()));
        txtNombre.setText(docente.getNombre());
        txtDireccion.setText(docente.getDireccion());
        txtFechaNaci.setText(docente.getFechaNac().toString());
        txtTalla.setText(String.valueOf(docente.getTalla()));
        txtCorreo.setText(docente.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaNaci = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnPromedioEdad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jPanel1.setLayout(null);

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 52, 21);

        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 80, 21);
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(170, 10, 160, 35);
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(170, 90, 160, 35);

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrabar);
        btnGrabar.setBounds(370, 20, 110, 35);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(370, 80, 110, 35);

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrimero);
        btnPrimero.setBounds(10, 300, 110, 35);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior);
        btnAnterior.setBounds(130, 300, 110, 35);

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente);
        btnSiguiente.setBounds(250, 300, 110, 35);

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUltimo);
        btnUltimo.setBounds(370, 300, 110, 35);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(10, 350, 110, 35);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(130, 350, 110, 35);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(250, 350, 110, 35);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir);
        btnImprimir.setBounds(370, 350, 110, 35);

        jLabel3.setText("Fecha (yyyy-MM-dd)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 136, 21);

        jLabel4.setText("Talla (metros):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 100, 21);

        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 48, 21);

        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 60, 58, 21);
        jPanel1.add(txtFechaNaci);
        txtFechaNaci.setBounds(170, 130, 160, 35);
        jPanel1.add(txtTalla);
        txtTalla.setBounds(170, 170, 160, 35);
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(170, 210, 160, 35);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(170, 50, 160, 35);

        btnPromedioEdad.setText("Promedio Edad");
        btnPromedioEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioEdadActionPerformed(evt);
            }
        });
        jPanel1.add(btnPromedioEdad);
        btnPromedioEdad.setBounds(370, 200, 110, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        limpiarCajasTexto();
        habilitarBotonesMovimiento(false);
        habilitarBotonesEdicion(false);
        habilitarCajasTexto(true);
        txtCodigo.setRequestFocusEnabled(true);
        agregando = true;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        docenteDAO.siguiente();
        cargarDatos();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        docenteDAO.ultimo();
        cargarDatos();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        docenteDAO.primero();
        cargarDatos();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        docenteDAO.anterior();
        cargarDatos();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        int codigo = Integer.parseInt(txtCodigo.getText());
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        LocalDate fecha = LocalDate.parse(txtFechaNaci.getText());
        double talla = Double.parseDouble(txtTalla.getText());
        String correo = txtCorreo.getText();

        Docente docente = new Docente(codigo, nombre, direccion, fecha, talla, correo);

        if (agregando) {
            docenteDAO.agregar(docente);
            limpiarCajasTexto();
            JOptionPane.showMessageDialog(null, "Agregado");
        } else {
            docenteDAO.modificar(docente);
            limpiarCajasTexto();
            JOptionPane.showMessageDialog(rootPane, "Modificado");
        }

        habilitarBotonesMovimiento(true);
        habilitarBotonesEdicion(true);
        habilitarCajasTexto(false);
        cargarDatos();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCajasTexto();
        habilitarCajasTexto(false);
        if (docenteDAO.esVacio()) {
            habilitarBotonesEdicion(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnImprimir.setEnabled(false);
            return;
        }
        habilitarBotonesMovimiento(true);
        habilitarBotonesEdicion(true);

        cargarDatos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        habilitarBotonesMovimiento(false);
        habilitarCajasTexto(true);
        habilitarBotonesEdicion(false);
        agregando = false;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        docenteDAO.eliminar();
        if (docenteDAO.esVacio()) {
            habilitarBotonesMovimiento(false);
            habilitarBotonesEdicion(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnImprimir.setEnabled(false);
            limpiarCajasTexto();
        } else {
            cargarDatos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String datos = docenteDAO.imprimir();
        JOptionPane.showMessageDialog(rootPane, datos);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPromedioEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioEdadActionPerformed
        if (!docenteDAO.esVacio()) {
            JOptionPane.showMessageDialog(null, docenteDAO.calcularPromedioEdad());
        }
    }//GEN-LAST:event_btnPromedioEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FraDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnPromedioEdad;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNaci;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTalla;
    // End of variables declaration//GEN-END:variables
}
